// examples/vue/src/FullEditor.vue
<script setup lang="ts">
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'
import { onBeforeUnmount, onMounted, useTemplateRef } from 'vue'

/**
 * The whole editor, mounted from Vue's lifecycle.
 *
 * `onMounted` rather than `setup`: the mount reaches for `window` and
 * `document` immediately, and `setup` also runs on the server. Vue gives the
 * element only once the component is in the DOM, which is exactly when the
 * editor can build itself into it.
 */
const host = useTemplateRef<HTMLDivElement>('host')
let editor: FullEditor | null = null

onMounted(() => {
  if (!host.value) return
  editor = mountFullEditor({
    element: host.value,
    namespace: 'trevixal:vue',
    languages: uiLanguageLoaders,
    aboutRows: [{ term: 'Framework', description: 'Vue 3, mounted from onMounted' }],
  })
})

onBeforeUnmount(() => {
  editor?.destroy()
  editor = null
})
</script>

<template>
  <div ref="host" data-testid="full-editor" />
</template>

// examples/angular/src/full-editor.component.ts
import {
  Component,
  DestroyRef,
  type ElementRef,
  afterNextRender,
  inject,
  viewChild,
} from '@angular/core'
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'

/**
 * The whole editor, mounted from Angular's lifecycle.
 *
 * `afterNextRender` rather than a constructor or `ngOnInit`: the mount reaches
 * for `window` and `document` immediately, and `afterNextRender` is the one
 * hook Angular guarantees never runs on the server. It also runs outside
 * change detection, which is the point. Nothing the editor does afterwards
 * passes through Angular at all.
 */
@Component({
  selector: 'app-full-editor',
  standalone: true,
  template: '<div #host data-testid="full-editor"></div>',
})
export class FullEditorComponent {
  private readonly host = viewChild.required<ElementRef<HTMLElement>>('host')
  private editor: FullEditor | null = null

  constructor() {
    afterNextRender(() => {
      this.editor = mountFullEditor({
        element: this.host().nativeElement,
        namespace: 'trevixal:angular',
        languages: uiLanguageLoaders,
        aboutRows: [
          { term: 'Framework', description: 'Angular 22, zoneless, mounted after render' },
        ],
      })
    })
    inject(DestroyRef).onDestroy(() => {
      this.editor?.destroy()
      this.editor = null
    })
  }
}
