// examples/svelte/src/FullEditor.svelte
<script lang="ts">
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'

/**
 * The whole editor, mounted from a Svelte effect.
 *
 * `$effect` rather than the module body: the mount reaches for `window` and
 * `document` immediately, and only an effect is guaranteed to run in the
 * browser after the element exists. The function it returns is the teardown
 * Svelte calls when the component goes away.
 */
let host: HTMLDivElement

$effect(() => {
  const editor: FullEditor = mountFullEditor({
    element: host,
    namespace: 'trevixal:svelte',
    languages: uiLanguageLoaders,
    aboutRows: [{ term: 'Framework', description: 'Svelte 5, mounted from an effect' }],
  })
  return () => editor.destroy()
})
</script>

<div bind:this={host} data-testid="full-editor"></div>

// examples/nuxt/app/components/FullEditor.vue
<script setup lang="ts">
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'
import { onBeforeUnmount, onMounted, useTemplateRef } from 'vue'

/**
 * The whole editor, mounted from Nuxt's client lifecycle.
 *
 * `onMounted` never runs on the server, so the mount, which reaches for
 * `window` in its first statement, is safe here even though the rest of the
 * page is prerendered. `<ClientOnly>` around this component in `app.vue` is
 * what keeps the *import* off the server too.
 */
const host = useTemplateRef<HTMLDivElement>('host')
let editor: FullEditor | null = null

onMounted(() => {
  if (!host.value) return
  editor = mountFullEditor({
    element: host.value,
    namespace: 'trevixal:nuxt',
    languages: uiLanguageLoaders,
    aboutRows: [{ term: 'Framework', description: 'Nuxt 4, inside <ClientOnly>' }],
  })
})

onBeforeUnmount(() => {
  editor?.destroy()
  editor = null
})
</script>

<template>
  <div ref="host" data-testid="full-editor" />
</template>
