// examples/nuxt/app/components/FullEditor.vue
<script setup lang="ts">
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'
import { onBeforeUnmount, onMounted, useTemplateRef } from 'vue'

/**
 * The whole editor, mounted from Nuxt's client lifecycle.
 *
 * `onMounted` never runs on the server, so the mount, which reaches for
 * `window` in its first statement, is safe here even though the rest of the
 * page is prerendered. `<ClientOnly>` around this component in `app.vue` is
 * what keeps the *import* off the server too.
 */
const host = useTemplateRef<HTMLDivElement>('host')
let editor: FullEditor | null = null

onMounted(() => {
  if (!host.value) return
  editor = mountFullEditor({
    element: host.value,
    namespace: 'trevixal:nuxt',
    languages: uiLanguageLoaders,
    aboutRows: [{ term: 'Framework', description: 'Nuxt 4, inside <ClientOnly>' }],
  })
})

onBeforeUnmount(() => {
  editor?.destroy()
  editor = null
})
</script>

<template>
  <div ref="host" data-testid="full-editor" />
</template>

// examples/next/app/full-editor.tsx
'use client'

import { mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'
import { useEffect, useRef } from 'react'

/**
 * The whole editor, mounted from a client effect.
 *
 * `'use client'` is not enough on its own. It says "send this component's code
 * to the browser", not "do not render it on the server", Next still renders
 * a client component once on the server to produce the initial HTML. The
 * module-level import of `@trevixal/editor-kit` would then be evaluated in
 * Node, and the page would ask for the CSS it never sent. The `ssr: false`
 * dynamic import in `page.tsx` is what keeps that from happening; this file
 * assumes it and reaches straight for the DOM.
 */
export default function FullEditor() {
  const host = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const element = host.current
    if (!element) return
    const editor = mountFullEditor({
      element,
      namespace: 'trevixal:next',
      languages: uiLanguageLoaders,
      aboutRows: [{ term: 'Framework', description: 'Next.js App Router, client-only' }],
    })
    return () => editor.destroy()
  }, [])

  return <div ref={host} data-testid="full-editor" />
}
