// examples/vue/src/FullEditor.vue
<script setup lang="ts">
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'
import { onBeforeUnmount, onMounted, useTemplateRef } from 'vue'

/**
 * The whole editor, mounted from Vue's lifecycle.
 *
 * `onMounted` rather than `setup`: the mount reaches for `window` and
 * `document` immediately, and `setup` also runs on the server. Vue gives the
 * element only once the component is in the DOM, which is exactly when the
 * editor can build itself into it.
 */
const host = useTemplateRef<HTMLDivElement>('host')
let editor: FullEditor | null = null

onMounted(() => {
  if (!host.value) return
  editor = mountFullEditor({
    element: host.value,
    namespace: 'trevixal:vue',
    languages: uiLanguageLoaders,
    aboutRows: [{ term: 'Framework', description: 'Vue 3, mounted from onMounted' }],
  })
})

onBeforeUnmount(() => {
  editor?.destroy()
  editor = null
})
</script>

<template>
  <div ref="host" data-testid="full-editor" />
</template>

// examples/svelte/src/FullEditor.svelte
<script lang="ts">
import { type FullEditor, mountFullEditor } from '@trevixal/editor-kit'
import { uiLanguageLoaders } from '@trevixal/ui/locales'

/**
 * The whole editor, mounted from a Svelte effect.
 *
 * `$effect` rather than the module body: the mount reaches for `window` and
 * `document` immediately, and only an effect is guaranteed to run in the
 * browser after the element exists. The function it returns is the teardown
 * Svelte calls when the component goes away.
 */
let host: HTMLDivElement

$effect(() => {
  const editor: FullEditor = mountFullEditor({
    element: host,
    namespace: 'trevixal:svelte',
    languages: uiLanguageLoaders,
    aboutRows: [{ term: 'Framework', description: 'Svelte 5, mounted from an effect' }],
  })
  return () => editor.destroy()
})
</script>

<div bind:this={host} data-testid="full-editor"></div>
